---
- name: Running REST API 
  hosts: localhost
#  vars:
#    job_template_id: 44
#    vmname: myvmname
 
  tasks:
    - name: Invoking REST API
      uri:
        url: https://18.216.19.92/api/v1/
		validate_certs: false
        method: POST
        user: admin
        password: ansible@123
        status_code: 202
#        body: 
#          extra_vars:
#            node_name: "{{ vmname }}"
        body_format: json